# Site settings
title: "Informatics and Multimedia Engineering"
description: "Multimedia Engineering at ISEL"
url: "https://pedro.fazenda.io"
baseurl: ""  # leave empty for user/custom domain

# Author info
author: "Pedro Fazenda"
email: "pedro.fazenda@isel.pt"

# Theme
remote_theme: pjekyll-theme-minimal
plugins:
  - jekyll-remote-theme

# Social links (used by footer or optional header links)
social:
  email: "pedro.fazenda@isel.pt"
  github: "pfazenda"
  linkedin: "pedrofazenda"

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Defaults for posts
defaults:
  - scope:
      path: ""          # applies to all files
      type: "posts"
    values:
      layout: "post"
      author: "Pedro Fazenda"

# Optional: include assets folder
include: ["assets"]
