# Site settings
title: "Informatics and Multimedia Engineering"
description: "Multimedia Engineering at [https://www.isel.pt/](ISEL)"
url: "https://pedro.fazenda.io"   # Use your GitHub Pages custom domain or username page URL
baseurl: ""                        # Leave empty because this is a user/organization site

# Author info
author:
  name: "Pedro Fazenda"
  email: "pedro.fazenda@isel.pt"

# Theme
theme: jekyll-theme-cayman

# Social links
social:
  email: "pedro.fazenda@isel.pt"
  github: "pfazenda"
  linkedin: "https://www.linkedin.com/in/pedrofazenda/"

# Markdown settings
markdown: kramdown
highlighter: rouge

# Defaults for posts
defaults:
  - scope:
      path: ""          # Applies to all files
      type: "posts"     # For posts
    values:
      layout: "post"
      author: "Pedro Fazenda"

# Optional: make sure assets are served correctly
# This is default behavior, but explicitly allows files in 'assets/' to be included
include: ["assets"]
